apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: users-service-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: users-service-secrets
    creationPolicy: Owner
  data:
  - secretKey: TABLE_NAME
    remoteRef:
      key: USERS_SECRET_NAME
      property: table_name
  - secretKey: AWS_REGION
    remoteRef:
      key: USERS_SECRET_NAME
      property: aws_region
