apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: login-service-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: login-service-secrets
    creationPolicy: Owner
  data:
  - secretKey: COGNITO_USER_POOL_ID
    remoteRef:
      key: LOGIN_SECRET_NAME
      property: user_pool_id
  - secretKey: COGNITO_CLIENT_ID
    remoteRef:
      key: LOGIN_SECRET_NAME
      property: client_id
  - secretKey: AWS_REGION
    remoteRef:
      key: LOGIN_SECRET_NAME
      property: aws_region
