apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: users-service-scaledobject
spec:
  scaleTargetRef:
    name: users-service
  minReplicaCount: 2
  maxReplicaCount: 5
  cooldownPeriod: 60
  pollingInterval: 15
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"
